apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: shacl-api
  name: shacl-api-svc
spec:
  type: ClusterIP
  ports:
    - name: "8001"
      port: 8001
      targetPort: 15400
  selector:
    app.kubernetes.io/name: shacl-api
