name: Release Helm Charts

on:
  push:
    tags:
      # This is used to trigger the release build.
      - "chart-*"

jobs:
  charts:
    permissions:
      contents: write
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: tools/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
